CREATE TABLE USERMASTER (
    ID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    USERNAME VARCHAR(100) UNIQUE NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    ADDDATE datetime,
    LASTLOGIN datetime
);

CREATE TABLE INVENTORYCAPTURE (
    ID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    OWNER VARCHAR(50) NOT NULL,
    LOCATION VARCHAR(20) NOT NULL,
    SKU VARCHAR(20) NOT NULL,
    LPN VARCHAR(20),
    UOM VARCHAR(10) NOT NULL,
    QTY INT NOT NULL,
    STATUS CHAR(1) DEFAULT '',
    USERNAME VARCHAR(50) NOT NULL,
    ADDDATE DATETIME NOT NULL
);

CREATE TABLE DOWNLOADTABLE (
    ID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    OWNER VARCHAR(50) NOT NULL,
    ASNNUMBER VARCHAR(50) NOT NULL,
    LINENUMBER VARCHAR(10) NOT NULL,
    LOCATION VARCHAR(20) NOT NULL,
    SKU VARCHAR(20) NOT NULL,
    LPN VARCHAR(20) NOT NULL,
    UOM VARCHAR(10) NOT NULL,
    QTY INT NOT NULL,
    STATUS CHAR(1) DEFAULT '0',
    DOWNLOADSTATUS VARCHAR(5)NOT NULL DEFAULT 'No',
    USERNAME VARCHAR(50) NOT NULL,
    ADDDATE DATETIME NOT NULL
);

CREATE TABLE NEXTUP (
    ID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    TYPE VARCHAR(10) DEFAULT 'ASN',
    STARTINGNUMBER VARCHAR(50) NOT NULL,
    ENDINGNUMBER VARCHAR(50) NOT NULL,
    CURRENTNUMBER VARCHAR(50) NOT NULL,
    NEXTNUMBER VARCHAR(50) NOT NULL,
    NUMBEROFLINES INT NOT NULL DEFAULT 3,
    PREFIX VARCHAR(10),
    ADDDATE DATETIME NOT NULL,
    USERCREATED VARCHAR(50) NOT NULL,
    DATEUPDATED DATETIME NOT NULL,
    USERUPDATED VARCHAR(50) NOT NULL
);